on:
  push:
  pull_request:

name: 🧪 Test

jobs:
  test-addon:
    runs-on: ubuntu-latest
    container: archlinux:base-devel

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v7

      - name: 👷 Build Dependencies
        run: "pacman --noconfirm -Syu base-devel cmake gcc git make pipewire pipewire-pulse"

      - name: 🍃 Install Node
        uses: actions/setup-node@v7
        with:
          node-version: 16

      - name: 🍃 Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 8
          run_install: false

      - name: 🔨 Build
        run: "pnpm install"

      - name: 🧪 Test
        run: |
          mkdir -p /run/user/$(id -u)
          export XDG_RUNTIME_DIR=/run/user/$(id -u)

          dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus --nofork --nopidfile --syslog-only &
          export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus

          pipewire &
          wireplumber &

          sleep 2
          pnpm run test
